// This file wires the tenant-auth controller and shared response mappers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"lina-core/pkg/plugin/capability/authcap/token"
	authapi "lina-plugin-linapro-tenant-core/backend/api/auth"
	v1 "lina-plugin-linapro-tenant-core/backend/api/auth/v1"
	"lina-plugin-linapro-tenant-core/backend/internal/service/membership"
	"lina-plugin-linapro-tenant-core/backend/internal/service/provider"
)

// ControllerV1 is the tenant auth controller.
type ControllerV1 struct {
	authSvc       token.Service
	membershipSvc membership.Service
	provider      *provider.Provider
}

// NewV1 creates and returns a new auth controller instance.
func NewV1(authSvc token.Service, membershipSvc membership.Service, providerSvc *provider.Provider) authapi.IAuthV1 {
	return &ControllerV1{
		authSvc:       authSvc,
		membershipSvc: membershipSvc,
		provider:      providerSvc,
	}
}

// toAPILoginTenant converts a service tenant option into an API DTO.
func toAPILoginTenant(item *membership.TenantInfo) *v1.LoginTenantItem {
	if item == nil {
		return nil
	}
	return &v1.LoginTenantItem{
		Id:     item.Id,
		Code:   item.Code,
		Name:   item.Name,
		Status: item.Status,
	}
}
