// This file wires the post controller and shared response mappers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	"lina-core/pkg/apitime"
	postapi "lina-plugin-org-center/backend/api/post"
	v1 "lina-plugin-org-center/backend/api/post/v1"
	postsvc "lina-plugin-org-center/backend/internal/service/post"
)

// ControllerV1 is the post controller.
type ControllerV1 struct {
	postSvc postsvc.Service // post service
}

// NewV1 creates and returns a new post controller instance.
func NewV1(postSvc postsvc.Service) postapi.IPostV1 {
	return &ControllerV1{postSvc: postSvc}
}

// toAPIPostItem converts the service-layer post entity into the API DTO projection.
func toAPIPostItem(entity *postsvc.PostEntity) v1.PostItem {
	if entity == nil {
		return v1.PostItem{}
	}
	return v1.PostItem{
		Id:        entity.Id,
		DeptId:    entity.DeptId,
		Code:      entity.Code,
		Name:      entity.Name,
		Sort:      entity.Sort,
		Status:    entity.Status,
		Remark:    entity.Remark,
		CreatedAt: apitime.Milli(entity.CreatedAt),
		UpdatedAt: apitime.Milli(entity.UpdatedAt),
	}
}
