// This file wires the AI invocation-log controller and response projection helpers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package invocation

import (
	"lina-core/pkg/apitime"
	"lina-plugin-linapro-ai-core/backend/api/invocation"
	v1 "lina-plugin-linapro-ai-core/backend/api/invocation/v1"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles masked AI invocation-log APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns invocation-log query logic.
}

// NewV1 creates and returns a new AI invocation-log controller instance.
func NewV1(aiSvc aisvc.Service) invocation.IInvocationV1 {
	return &ControllerV1{aiSvc: aiSvc}
}

// toAPIInvocationItem converts a service invocation projection into API DTO shape.
func toAPIInvocationItem(item *aisvc.InvocationItem) *v1.InvocationItem {
	if item == nil {
		return nil
	}
	return &v1.InvocationItem{
		Id:                   item.Id,
		RequestId:            item.RequestId,
		CapabilityType:       item.CapabilityType,
		CapabilityMethod:     item.CapabilityMethod,
		Purpose:              item.Purpose,
		TierCode:             item.TierCode,
		SourcePluginId:       item.SourcePluginId,
		TenantId:             item.TenantId,
		UserId:               item.UserId,
		ProviderId:           item.ProviderId,
		ModelId:              item.ModelId,
		ProviderName:         item.ProviderName,
		ModelName:            item.ModelName,
		Protocol:             item.Protocol,
		ThinkingEffort:       item.ThinkingEffort,
		Status:               item.Status,
		InputTokens:          item.InputTokens,
		OutputTokens:         item.OutputTokens,
		LatencyMs:            item.LatencyMs,
		AssetSummaryJson:     item.AssetSummaryJson,
		OperationSummaryJson: item.OperationSummaryJson,
		MetadataSummaryJson:  item.MetadataSummaryJson,
		ErrorCode:            item.ErrorCode,
		ErrorSummary:         item.ErrorSummary,
		CreatedAt:            milliValue(apitime.Milli(item.CreatedAt)),
	}
}

// toAPIProviderOperationItem converts a service provider operation projection into API DTO shape.
func toAPIProviderOperationItem(item *aisvc.ProviderOperationItem) *v1.ProviderOperationItem {
	if item == nil {
		return nil
	}
	return &v1.ProviderOperationItem{
		Id:               item.Id,
		OperationRef:     item.OperationRef,
		CapabilityType:   item.CapabilityType,
		CapabilityMethod: item.CapabilityMethod,
		Purpose:          item.Purpose,
		SourcePluginId:   item.SourcePluginId,
		ProviderId:       item.ProviderId,
		ModelId:          item.ModelId,
		ProviderName:     item.ProviderName,
		ModelName:        item.ModelName,
		Protocol:         item.Protocol,
		Status:           item.Status,
		NextPollAfterMs:  item.NextPollAfterMs,
		ExpiresAt:        milliValue(apitime.Milli(item.ExpiresAt)),
		AssetSummaryJson: item.AssetSummaryJson,
		ErrorCode:        item.ErrorCode,
		ErrorSummary:     item.ErrorSummary,
		CreatedAt:        milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:        milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// milliValue projects optional millisecond timestamps to zero for absent fields.
func milliValue(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}
