// This file wires the platform tenant controller and shared response mappers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package platform

import (
	"lina-core/pkg/apitime"
	platformapi "lina-plugin-multi-tenant/backend/api/platform"
	v1 "lina-plugin-multi-tenant/backend/api/platform/v1"
	"lina-plugin-multi-tenant/backend/internal/service/impersonate"
	tenantsvc "lina-plugin-multi-tenant/backend/internal/service/tenant"
)

// ControllerV1 is the platform multi-tenant controller.
type ControllerV1 struct {
	tenantSvc      tenantsvc.Service
	impersonateSvc impersonate.Service
}

// NewV1 creates and returns a new platform controller instance.
func NewV1(tenantSvc tenantsvc.Service, impersonateSvc impersonate.Service) platformapi.IPlatformV1 {
	return &ControllerV1{
		tenantSvc:      tenantSvc,
		impersonateSvc: impersonateSvc,
	}
}

// toAPITenant converts a service tenant into an API tenant DTO.
func toAPITenant(item *tenantsvc.Entity) *v1.TenantItem {
	if item == nil {
		return nil
	}
	return &v1.TenantItem{
		Id:        item.Id,
		Code:      item.Code,
		Name:      item.Name,
		Status:    item.Status,
		Remark:    item.Remark,
		CreatedAt: apitime.MilliFromString(item.CreatedAt),
	}
}
