// This file wires the AI provider controller and response projection helpers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package provider

import (
	"lina-core/pkg/apitime"
	"lina-plugin-linapro-ai-core/backend/api/provider"
	v1 "lina-plugin-linapro-ai-core/backend/api/provider/v1"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles AI provider and provider-owned model APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns provider and model management logic.
}

// NewV1 creates and returns a new AI provider controller instance.
func NewV1(aiSvc aisvc.Service) provider.IProviderV1 {
	return &ControllerV1{aiSvc: aiSvc}
}

// toAPIProviderItem converts a service provider projection into API DTO shape.
func toAPIProviderItem(item *aisvc.ProviderItem) *v1.ProviderItem {
	if item == nil {
		return nil
	}
	return &v1.ProviderItem{
		Id:                   item.Id,
		Name:                 item.Name,
		WebsiteUrl:           item.WebsiteUrl,
		Remark:               item.Remark,
		Enabled:              item.Enabled,
		ModelCount:           item.ModelCount,
		EnabledModelCount:    item.EnabledModelCount,
		EndpointCount:        item.EndpointCount,
		EnabledEndpointCount: item.EnabledEndpointCount,
		Models:               toAPIProviderModelSummaryItems(item.Models),
		Endpoints:            toAPIProviderEndpointItems(item.Endpoints),
		CreatedAt:            milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:            milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// toAPIProviderEndpointItems converts service endpoint summaries into API DTOs.
func toAPIProviderEndpointItems(items []*aisvc.ProviderEndpointItem) []*v1.ProviderEndpointItem {
	list := make([]*v1.ProviderEndpointItem, 0, len(items))
	for _, item := range items {
		list = append(list, toAPIProviderEndpointItem(item))
	}
	return list
}

// toAPIProviderEndpointItem converts one service endpoint projection into API DTO shape.
func toAPIProviderEndpointItem(item *aisvc.ProviderEndpointItem) *v1.ProviderEndpointItem {
	if item == nil {
		return nil
	}
	return &v1.ProviderEndpointItem{
		Id:           item.Id,
		ProviderId:   item.ProviderId,
		Protocol:     item.Protocol,
		BaseUrl:      item.BaseUrl,
		SecretRef:    item.SecretRef,
		Enabled:      item.Enabled,
		MetadataJson: item.MetadataJson,
		CreatedAt:    milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:    milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// toServiceProviderEndpointSaveInputs converts provider form endpoint payloads into service inputs.
func toServiceProviderEndpointSaveInputs(items []*v1.ProviderEndpointSaveItem, providerID int64) []aisvc.ProviderEndpointSaveInput {
	if items == nil {
		return nil
	}
	list := make([]aisvc.ProviderEndpointSaveInput, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		list = append(list, aisvc.ProviderEndpointSaveInput{
			Id:           item.Id,
			ProviderId:   providerID,
			Protocol:     item.Protocol,
			BaseUrl:      item.BaseUrl,
			SecretRef:    item.SecretRef,
			Enabled:      item.Enabled,
			MetadataJson: item.MetadataJson,
		})
	}
	return list
}

// toAPIProviderModelSummaryItems converts service model summaries into API DTOs.
func toAPIProviderModelSummaryItems(items []*aisvc.ProviderModelSummaryItem) []*v1.ProviderModelSummaryItem {
	list := make([]*v1.ProviderModelSummaryItem, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}
		list = append(list, &v1.ProviderModelSummaryItem{
			Id:        item.Id,
			ModelName: item.ModelName,
			Protocol:  item.Protocol,
			Enabled:   item.Enabled,
		})
	}
	return list
}

// toAPIModelItem converts a service model projection into API DTO shape.
func toAPIModelItem(item *aisvc.ModelItem) *v1.ModelItem {
	if item == nil {
		return nil
	}
	return &v1.ModelItem{
		Id:         item.Id,
		ProviderId: item.ProviderId,
		EndpointId: item.EndpointId,
		ModelName:  item.ModelName,
		Protocol:   item.Protocol,
		Source:     item.Source,
		Enabled:    item.Enabled,
		CreatedAt:  milliValue(apitime.Milli(item.CreatedAt)),
		UpdatedAt:  milliValue(apitime.Milli(item.UpdatedAt)),
	}
}

// milliValue projects optional millisecond timestamps to zero for absent fields.
func milliValue(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}
