// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// invocationDao is the data access object for the table plugin_linapro_ai_invocation.
// You can define custom methods on it to extend its functionality as needed.
type invocationDao struct {
	*internal.InvocationDao
}

var (
	// Invocation is a globally accessible object for table plugin_linapro_ai_invocation operations.
	Invocation = invocationDao{internal.NewInvocationDao()}
)

// Add your custom methods and functionality below.
