// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// modelDao is the data access object for the table plugin_linapro_ai_model.
// You can define custom methods on it to extend its functionality as needed.
type modelDao struct {
	*internal.ModelDao
}

var (
	// Model is a globally accessible object for table plugin_linapro_ai_model operations.
	Model = modelDao{internal.NewModelDao()}
)

// Add your custom methods and functionality below.
