// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// modelCapabilityDao is the data access object for the table plugin_linapro_ai_model_capability.
// You can define custom methods on it to extend its functionality as needed.
type modelCapabilityDao struct {
	*internal.ModelCapabilityDao
}

var (
	// ModelCapability is a globally accessible object for table plugin_linapro_ai_model_capability operations.
	ModelCapability = modelCapabilityDao{internal.NewModelCapabilityDao()}
)

// Add your custom methods and functionality below.
