// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// providerEndpointDao is the data access object for the table plugin_linapro_ai_provider_endpoint.
// You can define custom methods on it to extend its functionality as needed.
type providerEndpointDao struct {
	*internal.ProviderEndpointDao
}

var (
	// ProviderEndpoint is a globally accessible object for table plugin_linapro_ai_provider_endpoint operations.
	ProviderEndpoint = providerEndpointDao{internal.NewProviderEndpointDao()}
)

// Add your custom methods and functionality below.
