// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// providerDao is the data access object for the table plugin_linapro_ai_provider.
// You can define custom methods on it to extend its functionality as needed.
type providerDao struct {
	*internal.ProviderDao
}

var (
	// Provider is a globally accessible object for table plugin_linapro_ai_provider operations.
	Provider = providerDao{internal.NewProviderDao()}
)

// Add your custom methods and functionality below.
