// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// providerOperationDao is the data access object for the table plugin_linapro_ai_provider_operation.
// You can define custom methods on it to extend its functionality as needed.
type providerOperationDao struct {
	*internal.ProviderOperationDao
}

var (
	// ProviderOperation is a globally accessible object for table plugin_linapro_ai_provider_operation operations.
	ProviderOperation = providerOperationDao{internal.NewProviderOperationDao()}
)

// Add your custom methods and functionality below.
