// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-ai-core/backend/internal/dao/internal"
)

// tierDao is the data access object for the table plugin_linapro_ai_tier.
// You can define custom methods on it to extend its functionality as needed.
type tierDao struct {
	*internal.TierDao
}

var (
	// Tier is a globally accessible object for table plugin_linapro_ai_tier operations.
	Tier = tierDao{internal.NewTierDao()}
)

// Add your custom methods and functionality below.
