// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-tenant-core/backend/internal/dao/internal"
)

// domainDao is the data access object for the table plugin_linapro_tenant_core_domain.
// You can define custom methods on it to extend its functionality as needed.
type domainDao struct {
	*internal.DomainDao
}

var (
	// Domain is a globally accessible object for table plugin_linapro_tenant_core_domain operations.
	Domain = domainDao{internal.NewDomainDao()}
)

// Add your custom methods and functionality below.
