# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable"
        path: "internal"
        tables: >-
          plugin_linapro_org_core_dept,
          plugin_linapro_org_core_post,
          plugin_linapro_org_core_user_dept,
          plugin_linapro_org_core_user_post,
        removePrefix: "plugin_linapro_org_core_"
        importPrefix: "lina-plugin-linapro-org-core/backend/internal"
        descriptionTag: true
        noModelComment: true
        stdTime: true
        typeMapping:
          timestamp:
            type: "*time.Time"
            import: time
          "timestamp without time zone":
            type: "*time.Time"
            import: time
          timestamptz:
            type: "*time.Time"
            import: time
          "timestamp with time zone":
            type: "*time.Time"
            import: time
