// This file wires the content-notice controller and shared response mappers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice

import (
	"lina-core/pkg/apitime"
	noticeapi "lina-plugin-content-notice/backend/api/notice"
	v1 "lina-plugin-content-notice/backend/api/notice/v1"
	noticesvc "lina-plugin-content-notice/backend/internal/service/notice"
)

// ControllerV1 is the notice controller.
type ControllerV1 struct {
	noticeSvc noticesvc.Service // notice service
}

// NewV1 creates and returns a new notice controller instance.
func NewV1(noticeSvc noticesvc.Service) noticeapi.INoticeV1 {
	return &ControllerV1{noticeSvc: noticeSvc}
}

// toAPINoticeItem converts the service-layer plugin-local notice entity into
// the API DTO projection returned through HTTP responses.
func toAPINoticeItem(e *noticesvc.NoticeEntity) v1.NoticeItem {
	if e == nil {
		return v1.NoticeItem{}
	}
	return v1.NoticeItem{
		Id:        e.Id,
		Title:     e.Title,
		Type:      e.Type,
		Content:   e.Content,
		FileIds:   e.FileIds,
		Status:    e.Status,
		Remark:    e.Remark,
		CreatedBy: e.CreatedBy,
		UpdatedBy: e.UpdatedBy,
		CreatedAt: apitime.Milli(e.CreatedAt),
		UpdatedAt: apitime.Milli(e.UpdatedAt),
	}
}
