// This file defines the host-call demo DTOs for the dynamic plugin sample.

package v1

import "github.com/gogf/gf/v2/frame/g"

// HostCallDemoReq is the request for invoking the host call demo endpoint.
type HostCallDemoReq struct {
	g.Meta      `path:"/host-call-demo" method:"post" tags:"Dynamic Plugin Demo" summary:"Host calling capability demonstration" dc:"Demonstrate dynamic plugin calls to runtime, storage, network, and data capabilities through the unified host service model. The endpoint writes runtime logs, reads and writes isolated plugin storage, accesses governed upstreams, and performs structured CRUD on authorized data tables. Passing skipNetwork=1 skips external network requests for offline verification." access:"login" permission:"linapro-demo-dynamic:backend:view" operLog:"other"`
	SkipNetwork bool `json:"skipNetwork" dc:"Whether to skip external network requests: true=skip false=normal access, default is false when omitted" eg:"false"`
}

// HostCallDemoRes is the response for the host call demo endpoint.
type HostCallDemoRes struct {
	VisitCount int                     `json:"visitCount" dc:"The current cumulative number of visits, implemented through the runtime.state host service to achieve persistent counting" eg:"1"`
	PluginID   string                  `json:"pluginId" dc:"The unique identifier of the current plugin" eg:"linapro-demo-dynamic"`
	Runtime    *HostCallDemoRuntimeRes `json:"runtime" dc:"Summary of basic information returned by the runtime hosting service" eg:"{\"now\":1776132000000,\"uuid\":\"0d63c6a3-ec9d-4e39-a14f-d9b165a21ef9\",\"node\":\"node-1\"}"`
	Storage    *HostCallDemoStorageRes `json:"storage" dc:"storage hosting service executive summary" eg:"{\"pathPrefix\":\"host-call-demo/\",\"objectPath\":\"host-call-demo/demo.json\",\"stored\":true,\"listedCount\":1,\"deleted\":true}"`
	Network    *HostCallDemoNetworkRes `json:"network" dc:"network hosting service executive summary" eg:"{\"url\":\"https://example.com\",\"skipped\":false,\"statusCode\":200,\"contentType\":\"text/html\"}"`
	Data       *HostCallDemoDataRes    `json:"data" dc:"data host service executive summary" eg:"{\"table\":\"sys_plugin_node_state\",\"recordKey\":\"101\",\"listTotal\":1,\"countTotal\":1,\"updated\":true,\"deleted\":true}"`
	Message    string                  `json:"message" dc:"Host call demonstration information" eg:"Host service demo executed through runtime, storage, network, and data services."`
}

// HostCallDemoRuntimeRes describes runtime service results.
type HostCallDemoRuntimeRes struct {
	Now  *int64 `json:"now" dc:"Host current time as Unix timestamp in milliseconds" eg:"1776132000000"`
	UUID string `json:"uuid" dc:"The unique identifier generated by the host, used for resource isolation in this demonstration" eg:"0d63c6a3-ec9d-4e39-a14f-d9b165a21ef9"`
	Node string `json:"node" dc:"Current host node ID" eg:"node-1"`
}

// HostCallDemoStorageRes describes storage service results.
type HostCallDemoStorageRes struct {
	PathPrefix  string `json:"pathPrefix" dc:"The authorized logical path prefix used this time" eg:"host-call-demo/"`
	ObjectPath  string `json:"objectPath" dc:"The logical object path written this time" eg:"host-call-demo/demo.json"`
	Stored      bool   `json:"stored" dc:"Whether the object was successfully written and read back" eg:"true"`
	ListedCount int    `json:"listedCount" dc:"Number of objects listed by prefix" eg:"1"`
	Deleted     bool   `json:"deleted" dc:"Whether the temporary object was successfully deleted" eg:"true"`
}

// HostCallDemoNetworkRes describes network service results.
type HostCallDemoNetworkRes struct {
	URL         string `json:"url" dc:"The target URL or URL pattern of this application and access" eg:"https://example.com"`
	Skipped     bool   `json:"skipped" dc:"Whether network requests are skipped via skipNetwork=1" eg:"false"`
	StatusCode  int    `json:"statusCode" dc:"Upstream HTTP status code, 0 on skip or failure" eg:"200"`
	ContentType string `json:"contentType" dc:"Upstream response content type" eg:"text/html"`
	BodyPreview string `json:"bodyPreview" dc:"Upstream response body preview, returning up to the first 120 characters" eg:"<!doctype html>"`
	Error       string `json:"error" dc:"Error summary if the network request fails; empty if successful or skipped" eg:"Get https://example.com: context deadline exceeded"`
}

// HostCallDemoDataRes describes data service results.
type HostCallDemoDataRes struct {
	Table      string `json:"table" dc:"The host confirmation authorization data table name used this time" eg:"sys_plugin_node_state"`
	RecordKey  string `json:"recordKey" dc:"The record primary key value returned by the host" eg:"101"`
	ListTotal  int    `json:"listTotal" dc:"Total number of records retrieved by paging according to filter conditions" eg:"1"`
	CountTotal int    `json:"countTotal" dc:"The total number geted by executing count query based on the same filter conditions" eg:"1"`
	Updated    bool   `json:"updated" dc:"Whether the update is successfully completed and the updated record is read back" eg:"true"`
	Deleted    bool   `json:"deleted" dc:"Whether the temporary record was successfully deleted" eg:"true"`
}
