// This file wires the department controller and shared response mappers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dept

import (
	"lina-core/pkg/apitime"
	deptapi "lina-plugin-org-center/backend/api/dept"
	v1 "lina-plugin-org-center/backend/api/dept/v1"
	deptsvc "lina-plugin-org-center/backend/internal/service/dept"
)

// ControllerV1 is the department controller.
type ControllerV1 struct {
	deptSvc deptsvc.Service // department service
}

// NewV1 creates and returns a new department controller instance.
func NewV1(deptSvc deptsvc.Service) deptapi.IDeptV1 {
	return &ControllerV1{deptSvc: deptSvc}
}

// toAPIDeptItem converts the service-layer department entity into the API DTO projection.
func toAPIDeptItem(entity *deptsvc.DeptEntity) v1.DeptItem {
	if entity == nil {
		return v1.DeptItem{}
	}
	return v1.DeptItem{
		Id:        entity.Id,
		ParentId:  entity.ParentId,
		Ancestors: entity.Ancestors,
		Name:      entity.Name,
		Code:      entity.Code,
		OrderNum:  entity.OrderNum,
		Leader:    entity.Leader,
		Phone:     entity.Phone,
		Email:     entity.Email,
		Status:    entity.Status,
		Remark:    entity.Remark,
		CreatedAt: apitime.Milli(entity.CreatedAt),
		UpdatedAt: apitime.Milli(entity.UpdatedAt),
	}
}
