// This file wires the AI tier controller and response projection helpers.
// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tier

import (
	"lina-core/pkg/apitime"
	"lina-plugin-linapro-ai-core/backend/api/tier"
	v1 "lina-plugin-linapro-ai-core/backend/api/tier/v1"
	aisvc "lina-plugin-linapro-ai-core/backend/internal/service/ai"
)

// ControllerV1 handles AI capability tier APIs.
type ControllerV1 struct {
	aiSvc aisvc.Service // aiSvc owns tier management logic.
}

// NewV1 creates and returns a new AI tier controller instance.
func NewV1(aiSvc aisvc.Service) tier.ITierV1 {
	return &ControllerV1{aiSvc: aiSvc}
}

// toAPITierItem converts a service tier projection into API DTO shape.
func toAPITierItem(item *aisvc.TierItem) *v1.TierItem {
	if item == nil {
		return nil
	}
	dto := &v1.TierItem{
		Id:                   item.Id,
		CapabilityType:       item.CapabilityType,
		CapabilityMethod:     item.CapabilityMethod,
		Code:                 item.Code,
		DisplayName:          item.DisplayName,
		Description:          item.Description,
		DefaultEffort:        item.DefaultEffort,
		Enabled:              item.Enabled,
		SortOrder:            item.SortOrder,
		LastTestStatus:       item.LastTestStatus,
		LastTestLatencyMs:    item.LastTestLatencyMs,
		LastTestErrorSummary: item.LastTestErrorSummary,
		LastTestAt:           milliValue(apitime.Milli(item.LastTestAt)),
		UpdatedAt:            milliValue(apitime.Milli(item.UpdatedAt)),
	}
	if item.Binding != nil {
		dto.Binding = &v1.TierBindingItem{
			ProviderId:   item.Binding.ProviderId,
			ProviderName: item.Binding.ProviderName,
			ModelId:      item.Binding.ModelId,
			ModelName:    item.Binding.ModelName,
			Protocol:     item.Binding.Protocol,
			Enabled:      item.Binding.Enabled,
		}
	}
	return dto
}

// milliValue projects optional millisecond timestamps to zero for absent fields.
func milliValue(value *int64) int64 {
	if value == nil {
		return 0
	}
	return *value
}
